[profile.default]
src = "src"
test = "test"
libs = ["node_modules"]
remappings = [
  "forge-std/=node_modules/forge-std/src/",
  "ds-test/=node_modules/ds-test/src/",
  "@openzeppelin/=node_modules/@openzeppelin/contracts/",
  "solady/=node_modules/solady/src/",
]
gas_report = []
